version: "3.8"
services:
  mtg-search:
    build:
      context: .
      dockerfile: dev/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/__pycache__ # Exclude pycache from volume mount
    environment:
      - WEAVIATE_CLIENT_MODE=cloud
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    # Add your environment variables here
    # env_file:
    #   - .env
