services:
  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.9
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_API_BASED_MODULES: "true"
      ENABLE_MODULES: "text2vec-ollama,generative-ollama"
      CLUSTER_HOSTNAME: "node1"

  flask-app:
    container_name: flask-app
    build:
      context: ../
      dockerfile: ./dev/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
    depends_on:
      - weaviate
    volumes:
      - .:/app
    restart: on-failure:0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    stdin_open: true
    tty: true
volumes:
  weaviate_data:
